"""user status machine

Revision ID: 27db2f8507cd
Revises: 81709151d04f
Create Date: 2026-05-16 18:21:56.328617

"""
from alembic import op
import sqlalchemy as sa


revision = '27db2f8507cd'
down_revision = '81709151d04f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.String(length=16), nullable=False))
    op.add_column('users', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('admin_note', sa.String(length=500), nullable=False))
    op.add_column('users', sa.Column('status_changed_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'status_changed_at')
    op.drop_column('users', 'admin_note')
    op.drop_column('users', 'expires_at')
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
