"""init

Revision ID: 81709151d04f
Revises: 
Create Date: 2026-05-16 18:06:05.049172

"""
from alembic import op
import sqlalchemy as sa


revision = '81709151d04f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('license_key', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_license_key'), 'users', ['license_key'], unique=True)
    op.create_table('contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('company', sa.String(length=128), nullable=False),
    sa.Column('position', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('birthday', sa.String(length=10), nullable=False),
    sa.Column('anniversary', sa.String(length=10), nullable=False),
    sa.Column('memo', sa.Text(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_category'), 'contacts', ['category'], unique=False)
    op.create_index(op.f('ix_contacts_updated_at'), 'contacts', ['updated_at'], unique=False)
    op.create_index(op.f('ix_contacts_user_id'), 'contacts', ['user_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('hwid', sa.String(length=128), nullable=False),
    sa.Column('hostname', sa.String(length=128), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_hwid'), 'devices', ['hwid'], unique=False)
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('send_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('contact_name', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message_preview', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_send_logs_channel'), 'send_logs', ['channel'], unique=False)
    op.create_index(op.f('ix_send_logs_sent_at'), 'send_logs', ['sent_at'], unique=False)
    op.create_index(op.f('ix_send_logs_status'), 'send_logs', ['status'], unique=False)
    op.create_index(op.f('ix_send_logs_user_id'), 'send_logs', ['user_id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('contents', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_updated_at'), 'templates', ['updated_at'], unique=False)
    op.create_index(op.f('ix_templates_user_id'), 'templates', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_templates_user_id'), table_name='templates')
    op.drop_index(op.f('ix_templates_updated_at'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_send_logs_user_id'), table_name='send_logs')
    op.drop_index(op.f('ix_send_logs_status'), table_name='send_logs')
    op.drop_index(op.f('ix_send_logs_sent_at'), table_name='send_logs')
    op.drop_index(op.f('ix_send_logs_channel'), table_name='send_logs')
    op.drop_table('send_logs')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_hwid'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_contacts_user_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_updated_at'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_category'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_users_license_key'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
