"""payments table

Revision ID: dbff099ad682
Revises: 27db2f8507cd
Create Date: 2026-05-16 20:05:19.110107

"""
from alembic import op
import sqlalchemy as sa


revision = 'dbff099ad682'
down_revision = '27db2f8507cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('portone_payment_id', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('receipt_url', sa.Text(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_portone_payment_id'), 'payments', ['portone_payment_id'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_portone_payment_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
